"""glasslink host SDK — pack MQTT cmds, publish, chart recipes."""

from __future__ import annotations

from glasslink.charts import bar_graph, gauge, pie
from glasslink.client import AckGate, Device
from glasslink.protocol import (
    BATCH_BYTES_MAX,
    BIND_SLOTS,
    ENC_RAW,
    FLAG_URI,
    GROUP_SLOTS,
    HDR_SIZE,
    INLINE_MAX,
    MAGIC,
    ROOT,
    TEXT_MAX,
    TYPE_BATCH,
    TYPE_BIND_DEFINE,
    TYPE_BIND_SET,
    TYPE_CLEAR,
    TYPE_CUBIC_TO,
    TYPE_FILL,
    TYPE_GROUP_DEFINE,
    TYPE_GROUP_DRAW,
    TYPE_LINE_TO,
    TYPE_MOVE_TO,
    TYPE_POLY,
    TYPE_RECT,
    TYPE_TEXT,
    batch_ops_bytes,
    check_inline_max,
    enc_id,
    encode_rgb,
    ensure_encode_rect,
    mqtt_client,
    pack_batch,
    pack_bind_define,
    pack_bind_set,
    pack_clear,
    pack_cubic_to,
    pack_fill_rect,
    pack_group_define,
    pack_group_draw,
    pack_line_to,
    pack_move_to,
    pack_poly,
    pack_rect,
    pack_text,
    peek_id_seq,
    rgb565_checker,
    rgb565_fill,
    rgb565_h_runs,
    topic_ack,
    topic_bind_set,
    topic_cmd,
    topic_lwt,
    topic_status,
)

__all__ = [
    "AckGate",
    "Device",
    "BATCH_BYTES_MAX",
    "BIND_SLOTS",
    "ENC_RAW",
    "FLAG_URI",
    "GROUP_SLOTS",
    "HDR_SIZE",
    "INLINE_MAX",
    "MAGIC",
    "ROOT",
    "TEXT_MAX",
    "bar_graph",
    "batch_ops_bytes",
    "check_inline_max",
    "enc_id",
    "encode_rgb",
    "ensure_encode_rect",
    "gauge",
    "mqtt_client",
    "pack_batch",
    "pack_bind_define",
    "pack_bind_set",
    "pack_clear",
    "pack_cubic_to",
    "pack_fill_rect",
    "pack_group_define",
    "pack_group_draw",
    "pack_line_to",
    "pack_move_to",
    "pack_poly",
    "pack_rect",
    "pack_text",
    "peek_id_seq",
    "pie",
    "rgb565_checker",
    "rgb565_fill",
    "rgb565_h_runs",
    "topic_ack",
    "topic_bind_set",
    "topic_cmd",
    "topic_lwt",
    "topic_status",
]

__version__ = "0.1.0"
