/*
 * Track B codec bench (docs/codec-harness.md).
 *
 * Usage:
 *   ./bench_codec [--class a,b] [--enc raw,delta_rle_v1] [--csv] [--md-out path]
 * Env: CLASS=…  ENC=…
 */

#include "codec.h"
#include "corpus_gen.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

typedef struct {
    const char *id;
    corpus_class_t cls;
    int w, h;
    unsigned seed;
} bench_case_t;

static const bench_case_t k_cases[] = {
    {"solid_32", CORPUS_SOLID, 32, 32, 1},
    {"solid_320x240", CORPUS_SOLID, 320, 240, 1},
    {"h_runs_64", CORPUS_H_RUNS, 64, 48, 1},
    {"v_runs_64", CORPUS_V_RUNS, 64, 48, 1},
    {"grid_32", CORPUS_GRID, 32, 32, 1},
    {"grid_128", CORPUS_GRID, 128, 128, 1},
    {"grad_h_64", CORPUS_GRADIENT_H, 64, 48, 1},
    {"grad_v_64", CORPUS_GRADIENT_V, 64, 48, 1},
    {"grad_2d_64", CORPUS_GRADIENT_2D, 64, 48, 1},
    {"ui_panel_128", CORPUS_UI_PANEL, 128, 128, 1},
    {"ui_panel_320x240", CORPUS_UI_PANEL, 320, 240, 1},
    {"ui_text_128", CORPUS_UI_TEXT, 128, 64, 1},
    {"ui_gauge_96", CORPUS_UI_GAUGE, 96, 96, 1},
    {"sparse_64", CORPUS_SPARSE_DIRTY, 64, 64, 1},
    {"sparse_320x240", CORPUS_SPARSE_DIRTY, 320, 240, 1},
    {"noise_32", CORPUS_NOISE_WHITE, 32, 32, 42},
    {"noise_64", CORPUS_NOISE_WHITE, 64, 48, 42},
    {"noise_1bit_64", CORPUS_NOISE_1BIT, 64, 48, 7},
    {"photo_soft_64", CORPUS_PHOTO_SOFT, 64, 48, 9},
    {"partial_tl_32", CORPUS_PARTIAL_TL, 32, 32, 1},
    {"partial_br_32", CORPUS_PARTIAL_BR, 32, 32, 1},
    {"adv_rle_32", CORPUS_ADVERSARIAL_RLE, 32, 32, 1},
    {"odd_319x1", CORPUS_GRADIENT_H, 319, 1, 1},
    {"odd_1x240", CORPUS_GRADIENT_V, 1, 240, 1},
    {"odd_3x5", CORPUS_GRID, 3, 5, 1},
    {"odd_8x8", CORPUS_UI_TEXT, 8, 8, 1},
};

enum { N_CASES = (int)(sizeof(k_cases) / sizeof(k_cases[0])) };

typedef struct {
    codec_enc_t enc;
    const char *name;
    int enabled;
} enc_sel_t;

typedef struct {
    double log_ratio_sum;
    int ratio_n;
    int expand_n;
    int fail_n;
    double dec_us_sum;
} agg_t;

static double now_us(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec * 1e6 + (double)ts.tv_nsec / 1e3;
}

static int class_wanted(const char *filter, corpus_class_t cls)
{
    char buf[256];
    char *tok;
    char *save = NULL;

    if (!filter || !filter[0] || strcmp(filter, "all") == 0) {
        return 1;
    }
    snprintf(buf, sizeof(buf), "%s", filter);
    for (tok = strtok_r(buf, ",;", &save); tok; tok = strtok_r(NULL, ",;", &save)) {
        while (*tok == ' ') {
            tok++;
        }
        if (strcmp(tok, corpus_class_name(cls)) == 0) {
            return 1;
        }
    }
    return 0;
}

static void enable_encs(enc_sel_t *encs, int n, const char *filter)
{
    char buf[128];
    char *tok;
    char *save = NULL;
    int i;

    if (!filter || !filter[0] || strcmp(filter, "all") == 0) {
        for (i = 0; i < n; i++) {
            encs[i].enabled = 1;
        }
        return;
    }
    for (i = 0; i < n; i++) {
        encs[i].enabled = 0;
    }
    snprintf(buf, sizeof(buf), "%s", filter);
    for (tok = strtok_r(buf, ",;", &save); tok; tok = strtok_r(NULL, ",;", &save)) {
        while (*tok == ' ') {
            tok++;
        }
        for (i = 0; i < n; i++) {
            if (strcmp(tok, encs[i].name) == 0 ||
                (strcmp(tok, "delta") == 0 &&
                 encs[i].enc == CODEC_ENC_DELTA_RLE_V1) ||
                (strcmp(tok, "delta_rle") == 0 &&
                 encs[i].enc == CODEC_ENC_DELTA_RLE_V1)) {
                encs[i].enabled = 1;
            }
        }
    }
}

static void agg_add(agg_t *a, double ratio, int expand, int ok, double dec_us)
{
    if (!ok) {
        a->fail_n++;
        return;
    }
    if (ratio > 0.0) {
        a->log_ratio_sum += log(ratio);
        a->ratio_n++;
    }
    if (expand) {
        a->expand_n++;
    }
    a->dec_us_sum += dec_us;
}

static double geo_mean(const agg_t *a)
{
    if (a->ratio_n <= 0) {
        return 0.0;
    }
    return exp(a->log_ratio_sum / (double)a->ratio_n);
}

static int is_primary_class(corpus_class_t cls)
{
    return cls == CORPUS_UI_PANEL || cls == CORPUS_UI_TEXT ||
           cls == CORPUS_UI_GAUGE || cls == CORPUS_SPARSE_DIRTY ||
           cls == CORPUS_SOLID || cls == CORPUS_H_RUNS || cls == CORPUS_V_RUNS;
}

static void print_header(int csv, FILE *md)
{
    if (csv) {
        printf("case,class,enc,w,h,raw,comp,ratio,save_pct,enc_us,dec_us,"
               "expand,ok\n");
        return;
    }
    printf("| case | class | enc | w | h | raw | comp | ratio | save%% | "
           "enc_us | dec_us | expand | ok |\n");
    printf("|------|-------|-----|---|---|-----|------|-------|-------|"
           "--------|--------|--------|----|\n");
    if (md) {
        fprintf(md,
                "# Codec bench MVP\n\n"
                "Generated by `make bench-codec`. Track B only — not a freeze.\n\n"
                "| case | class | enc | w | h | raw | comp | ratio | save%% | "
                "enc_us | dec_us | expand | ok |\n"
                "|------|-------|-----|---|---|-----|------|-------|-------|"
                "--------|--------|--------|----|\n");
    }
}

static void emit_row(int csv, FILE *md, const bench_case_t *c, const char *enc,
                     size_t raw_bytes, size_t len, double ratio, double save,
                     double enc_us, double dec_us, int expand, int ok)
{
    if (csv) {
        printf("%s,%s,%s,%d,%d,%zu,%zu,%.3f,%.1f,%.1f,%.1f,%d,%d\n", c->id,
               corpus_class_name(c->cls), enc, c->w, c->h, raw_bytes, len, ratio,
               save, enc_us, dec_us, expand, ok);
        return;
    }
    printf("| %s | %s | %s | %d | %d | %zu | %zu | %.2f | %.1f | %.1f | %.1f | "
           "%s | %s |\n",
           c->id, corpus_class_name(c->cls), enc, c->w, c->h, raw_bytes, len,
           ratio, save, enc_us, dec_us, expand ? "Y" : "", ok ? "Y" : "N");
    if (md) {
        fprintf(md,
                "| %s | %s | %s | %d | %d | %zu | %zu | %.2f | %.1f | %.1f | "
                "%.1f | %s | %s |\n",
                c->id, corpus_class_name(c->cls), enc, c->w, c->h, raw_bytes,
                len, ratio, save, enc_us, dec_us, expand ? "Y" : "",
                ok ? "Y" : "N");
    }
}

int main(int argc, char **argv)
{
    enc_sel_t encs[] = {
        {CODEC_ENC_RAW_RGB565, "raw", 1},
        {CODEC_ENC_DELTA_RLE_V1, "delta_rle_v1", 1},
    };
    const char *class_f = getenv("CLASS");
    const char *enc_f = getenv("ENC");
    int csv = 0;
    const char *md_out = NULL;
    FILE *md = NULL;
    agg_t agg_delta = {0};
    agg_t agg_ui = {0};
    int rows = 0;

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--csv") == 0) {
            csv = 1;
        } else if (strcmp(argv[i], "--class") == 0 && i + 1 < argc) {
            class_f = argv[++i];
        } else if (strcmp(argv[i], "--enc") == 0 && i + 1 < argc) {
            enc_f = argv[++i];
        } else if (strcmp(argv[i], "--md-out") == 0 && i + 1 < argc) {
            md_out = argv[++i];
        } else if (strcmp(argv[i], "-h") == 0 ||
                   strcmp(argv[i], "--help") == 0) {
            fprintf(stderr,
                    "Usage: %s [--class a,b] [--enc raw,delta_rle_v1] [--csv] "
                    "[--md-out path]\n",
                    argv[0]);
            return 0;
        }
    }
    enable_encs(encs, 2, enc_f);

    if (md_out) {
        md = fopen(md_out, "w");
        if (!md) {
            perror(md_out);
            return 1;
        }
    }

    print_header(csv, md);

    for (int ci = 0; ci < N_CASES; ci++) {
        const bench_case_t *c = &k_cases[ci];
        size_t px, raw_bytes;
        uint16_t *src;
        uint16_t *dst;

        if (!class_wanted(class_f, c->cls)) {
            continue;
        }
        px = (size_t)c->w * (size_t)c->h;
        raw_bytes = px * sizeof(uint16_t);
        src = (uint16_t *)malloc(raw_bytes);
        dst = (uint16_t *)malloc(raw_bytes);
        if (!src || !dst) {
            free(src);
            free(dst);
            fprintf(stderr, "oom\n");
            return 1;
        }
        if (corpus_fill(c->cls, src, c->w, c->h, c->seed) != 0) {
            fprintf(stderr, "gen fail %s\n", c->id);
            free(src);
            free(dst);
            return 1;
        }

        for (int ei = 0; ei < 2; ei++) {
            const enc_sel_t *e = &encs[ei];
            size_t bound, len = 0;
            uint8_t *buf;
            int rc, ok, expand;
            double t0, t1, enc_us, dec_us, ratio, save;

            if (!e->enabled) {
                continue;
            }
            bound = codec_encode_bound(e->enc, c->w, c->h);
            if (bound < raw_bytes + 16) {
                bound = raw_bytes * 2 + 64;
            }
            buf = (uint8_t *)malloc(bound);
            if (!buf) {
                free(src);
                free(dst);
                fprintf(stderr, "oom buf\n");
                return 1;
            }

            t0 = now_us();
            rc = codec_encode(e->enc, src, c->w, c->h, buf, bound, &len);
            t1 = now_us();
            enc_us = t1 - t0;
            if (rc != CODEC_OK) {
                emit_row(csv, md, c, e->name, raw_bytes, 0, 0, 0, 0, 0, 0, 0);
                free(buf);
                if (e->enc == CODEC_ENC_DELTA_RLE_V1) {
                    agg_delta.fail_n++;
                }
                continue;
            }

            memset(dst, 0xA5, raw_bytes);
            t0 = now_us();
            rc = codec_decode(e->enc, c->w, c->h, buf, len, dst);
            t1 = now_us();
            dec_us = t1 - t0;
            ok = (rc == CODEC_OK && memcmp(src, dst, raw_bytes) == 0);
            expand = (len > raw_bytes) ? 1 : 0;
            ratio = len ? (double)raw_bytes / (double)len : 0.0;
            save = raw_bytes ? 100.0 * (1.0 - (double)len / (double)raw_bytes)
                            : 0.0;

            emit_row(csv, md, c, e->name, raw_bytes, len, ratio, save, enc_us,
                     dec_us, expand, ok);

            if (e->enc == CODEC_ENC_DELTA_RLE_V1) {
                agg_add(&agg_delta, ratio, expand, ok, dec_us);
                if (is_primary_class(c->cls)) {
                    agg_add(&agg_ui, ratio, expand, ok, dec_us);
                }
            }
            rows++;
            free(buf);
        }
        free(src);
        free(dst);
    }

    if (!csv) {
        printf("\n## Summary (delta_rle_v1)\n\n");
        printf("- rows: %d\n", rows);
        printf("- geo-mean ratio (all filtered delta cases): %.3f  (n=%d)\n",
               geo_mean(&agg_delta), agg_delta.ratio_n);
        printf("- geo-mean ratio (ui/sparse/solid/runs): %.3f  (n=%d)\n",
               geo_mean(&agg_ui), agg_ui.ratio_n);
        printf("- expand count: %d  fail: %d\n", agg_delta.expand_n,
               agg_delta.fail_n);
        if (agg_delta.ratio_n > 0) {
            printf("- mean dec_us: %.1f\n",
                   agg_delta.dec_us_sum / (double)agg_delta.ratio_n);
        }
    }
    if (md) {
        fprintf(md,
                "\n## Summary (delta_rle_v1)\n\n"
                "- geo-mean ratio (all): **%.3f** (n=%d)\n"
                "- geo-mean ratio (ui/sparse/solid/runs): **%.3f** (n=%d)\n"
                "- expand: %d  fail: %d\n"
                "- mean dec_us: %.1f\n\n"
                "Host wall-clock only. Re-run: `make bench-codec`.\n\n"
                "## Notes\n\n"
                "- Profile knobs / `TUNE=sweep` deferred to Step 7.\n"
                "- Encoder policy tip: if `comp ≈ raw`, prefer `enc=raw` "
                "(noise/grid often expand).\n",
                geo_mean(&agg_delta), agg_delta.ratio_n, geo_mean(&agg_ui),
                agg_ui.ratio_n, agg_delta.expand_n, agg_delta.fail_n,
                agg_delta.ratio_n
                    ? agg_delta.dec_us_sum / (double)agg_delta.ratio_n
                    : 0.0);
        fclose(md);
    }
    return agg_delta.fail_n ? 2 : 0;
}
